### ISSUE TITLE
Don't really understand how to render a chart in Javascript

### ISSUE THREAD

**Issue by 2ndGAB** [kevinkhill/lavacharts-laravel#1]
Hello,
Sorry if it's not really the place to ask this question but I didn't get any answer from Stackoverflow and maybe you don't really pay attention to it as you don't have any defined tag.

I'm trying to render a chart on CakePHP framework but the problem is not related to the framework but to how to find the chart id from Javascript.

I explained my problem [here](http://stackoverflow.com/questions/43951860/how-to-render-a-lavachart-from-javascript) I think it's maybe not necessary to redo everything here.
So I would appreciate that get a look at it to help me.

Thanks a lot,
Alain

**Comment by kevinkhill** [comment]
I am going to copy this issue [over to the main repo](https://github.com/kevinkhill/lavacharts/issues/202), to track it with the others.

**Comment by kevinkhill** [comment]
We can continue this over there :+1:
